# Generated by Django 3.1.4 on 2020-12-04 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField(default='', null=True)),
                ('description', models.TextField(default='', max_length=500, null=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
