# Generated by Django 3.1.4 on 2020-12-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('description', models.TextField(default='', max_length=500)),
                ('updated_date', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
